export const STEP_1_COMPLETED = 'STEP_1_COMPLETED';
export const STEP_2_COMPLETED = 'STEP_2_COMPLETED';
export const STEP_3_COMPLETED = 'STEP_3_COMPLETED';
export const NEW_REGISTRATION = 'NEW_REGISTRATION';
